### PR TITLE
Terms of Service (Storage Terms)

### PR DESCRIPTION
**Pull request by bryanchriswhite**
@boshevski I'd like your feedback on whether we should go with the scrolling-body modal or not. There is a small issue introduced by it which is that the scrollbar drops below/behind the `.modal-footer` section as you get to the bottom of the `.modal-body`.

[Demo screencapture (HD - youtube)](https://youtu.be/SyFfyAc1R84)

storj-terms-modal-demo

### CODE REVIEW

**Comment by frdwrd** [comment]
The flow is good. Can we also host it on its own page, and have the modal link to that page?

**Comment by bryanchriswhite** [comment]
@frdwrd we were planning hosting it on the landing site as well. @boshevski either has already taken care of that, or will soon.

As far as a link to the landing site, where would you like that link to be in the modal? @boshevski thoughts?

**Comment by boshevski** [comment]
Here is a link to the Storage Terms of Service page: https://storj.io/terms-of-service.html
@frdwrd How do you mean "the modal link to that page"?

**Comment by frdwrd** [comment]
@bryanchriswhite I would put at the top of the modal, and I would say something like "A static version of this document can be found here."

A future consideration: It'd be nice in the future if we could have both the static page and the modal pull from the same location so that updating the ToS is easy.

**Comment by bryanchriswhite** [comment]
@frdwrd link added:
screen shot 2016-07-06 at 11 39 37 pm

**Comment by frdwrd** [comment]
Looks good. 👍

**Pull request merged**
