### PR TITLE
Add bitcoin payment option - Close 142

### PR DESCRIPTION
**Pull request by boshevski**
Please review and test.

### CODE REVIEW

**Comment by boshevski** [comment]
https://github.com/Storj/bridge-gui/issues/142

**Comment by barbaraliau** [comment]
Changes look good, but blocked until I can make the switch from old `storj 2.0` to `storj.js`

**Comment by boshevski** [comment]
Merge conflict resolved.

**Comment by super3** [comment]
@boshevski Another merge conflict

**Comment by super3** [comment]
@barbaraliau Can this be merged?

**Comment by barbaraliau** [comment]
@super3 Yep. LGTM.

**Pull request merged**
